//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typeform.Sdk.CSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Typeform.Sdk.CSharp.Resources.EnumText", typeof(EnumText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string Action_Divide {
            get {
                return ResourceManager.GetString("Action_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string Action_Jump {
            get {
                return ResourceManager.GetString("Action_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string Action_Multiply {
            get {
                return ResourceManager.GetString("Action_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string Action_Subtract {
            get {
                return ResourceManager.GetString("Action_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Attachment_Image {
            get {
                return ResourceManager.GetString("Attachment_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Attachment_Video {
            get {
                return ResourceManager.GetString("Attachment_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        public static string ButtonMode_Redirect {
            get {
                return ResourceManager.GetString("ButtonMode_Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ButtonMode_Reload {
            get {
                return ResourceManager.GetString("ButtonMode_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string ConditionOperation_Always {
            get {
                return ResourceManager.GetString("ConditionOperation_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        public static string ConditionOperation_BeginsWith {
            get {
                return ResourceManager.GetString("ConditionOperation_BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string ConditionOperation_Contains {
            get {
                return ResourceManager.GetString("ConditionOperation_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier than.
        /// </summary>
        public static string ConditionOperation_EarlierThan {
            get {
                return ResourceManager.GetString("ConditionOperation_EarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier than or on.
        /// </summary>
        public static string ConditionOperation_EarlierThanOrOn {
            get {
                return ResourceManager.GetString("ConditionOperation_EarlierThanOrOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string ConditionOperation_EndsWith {
            get {
                return ResourceManager.GetString("ConditionOperation_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string ConditionOperation_Equal {
            get {
                return ResourceManager.GetString("ConditionOperation_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater or equal than.
        /// </summary>
        public static string ConditionOperation_GreaterEqualThan {
            get {
                return ResourceManager.GetString("ConditionOperation_GreaterEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string ConditionOperation_GreaterThan {
            get {
                return ResourceManager.GetString("ConditionOperation_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        public static string ConditionOperation_Is {
            get {
                return ResourceManager.GetString("ConditionOperation_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not.
        /// </summary>
        public static string ConditionOperation_IsNot {
            get {
                return ResourceManager.GetString("ConditionOperation_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later than.
        /// </summary>
        public static string ConditionOperation_LaterThan {
            get {
                return ResourceManager.GetString("ConditionOperation_LaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later than or on.
        /// </summary>
        public static string ConditionOperation_LaterThanOrOn {
            get {
                return ResourceManager.GetString("ConditionOperation_LaterThanOrOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower or equal than.
        /// </summary>
        public static string ConditionOperation_LowerEqualThan {
            get {
                return ResourceManager.GetString("ConditionOperation_LowerEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower than.
        /// </summary>
        public static string ConditionOperation_LowerThan {
            get {
                return ResourceManager.GetString("ConditionOperation_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string ConditionOperation_NotContains {
            get {
                return ResourceManager.GetString("ConditionOperation_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal.
        /// </summary>
        public static string ConditionOperation_NotEqual {
            get {
                return ResourceManager.GetString("ConditionOperation_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on.
        /// </summary>
        public static string ConditionOperation_NotOn {
            get {
                return ResourceManager.GetString("ConditionOperation_NotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ConditionOperation_On {
            get {
                return ResourceManager.GetString("ConditionOperation_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Dollar.
        /// </summary>
        public static string Currency_AUD {
            get {
                return ResourceManager.GetString("Currency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian Real.
        /// </summary>
        public static string Currency_BRL {
            get {
                return ResourceManager.GetString("Currency_BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian Dollar.
        /// </summary>
        public static string Currency_CAD {
            get {
                return ResourceManager.GetString("Currency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss Franc.
        /// </summary>
        public static string Currency_CHF {
            get {
                return ResourceManager.GetString("Currency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Krone.
        /// </summary>
        public static string Currency_DKK {
            get {
                return ResourceManager.GetString("Currency_DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European Euro.
        /// </summary>
        public static string Currency_EUR {
            get {
                return ResourceManager.GetString("Currency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Britian Pound.
        /// </summary>
        public static string Currency_GBP {
            get {
                return ResourceManager.GetString("Currency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican Peso.
        /// </summary>
        public static string Currency_MXN {
            get {
                return ResourceManager.GetString("Currency_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian Krone.
        /// </summary>
        public static string Currency_NOK {
            get {
                return ResourceManager.GetString("Currency_NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish Krona.
        /// </summary>
        public static string Currency_SEK {
            get {
                return ResourceManager.GetString("Currency_SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Dollar.
        /// </summary>
        public static string Currency_USD {
            get {
                return ResourceManager.GetString("Currency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Month Year.
        /// </summary>
        public static string DateFormat_DayMonthYear {
            get {
                return ResourceManager.GetString("DateFormat_DayMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Day Year.
        /// </summary>
        public static string DateFormat_MonthDayYear {
            get {
                return ResourceManager.GetString("DateFormat_MonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Month Day.
        /// </summary>
        public static string DateFormat_YearMonthDay {
            get {
                return ResourceManager.GetString("DateFormat_YearMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash (-).
        /// </summary>
        public static string DateSeparator_Dash {
            get {
                return ResourceManager.GetString("DateSeparator_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot (.).
        /// </summary>
        public static string DateSeparator_Dot {
            get {
                return ResourceManager.GetString("DateSeparator_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash (/).
        /// </summary>
        public static string DateSeparator_Slash {
            get {
                return ResourceManager.GetString("DateSeparator_Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Field_Date {
            get {
                return ResourceManager.GetString("Field_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown.
        /// </summary>
        public static string Field_Dropdown {
            get {
                return ResourceManager.GetString("Field_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Field_Email {
            get {
                return ResourceManager.GetString("Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        public static string Field_FileUpload {
            get {
                return ResourceManager.GetString("Field_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Field_Group {
            get {
                return ResourceManager.GetString("Field_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string Field_Legal {
            get {
                return ResourceManager.GetString("Field_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Text.
        /// </summary>
        public static string Field_LongText {
            get {
                return ResourceManager.GetString("Field_LongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Choice.
        /// </summary>
        public static string Field_MultipleChoice {
            get {
                return ResourceManager.GetString("Field_MultipleChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Field_Number {
            get {
                return ResourceManager.GetString("Field_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion Scale.
        /// </summary>
        public static string Field_OpinionScale {
            get {
                return ResourceManager.GetString("Field_OpinionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Field_Payment {
            get {
                return ResourceManager.GetString("Field_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Choice.
        /// </summary>
        public static string Field_PictureChoice {
            get {
                return ResourceManager.GetString("Field_PictureChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Field_Rating {
            get {
                return ResourceManager.GetString("Field_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Text.
        /// </summary>
        public static string Field_ShortText {
            get {
                return ResourceManager.GetString("Field_ShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        public static string Field_Statement {
            get {
                return ResourceManager.GetString("Field_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Field_Website {
            get {
                return ResourceManager.GetString("Field_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes No.
        /// </summary>
        public static string Field_YesNo {
            get {
                return ResourceManager.GetString("Field_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string Language_Catalan {
            get {
                return ResourceManager.GetString("Language_Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (simplified).
        /// </summary>
        public static string Language_ChineseSimplified {
            get {
                return ResourceManager.GetString("Language_ChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (traditional).
        /// </summary>
        public static string Language_ChineseTraditional {
            get {
                return ResourceManager.GetString("Language_ChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string Language_Croatian {
            get {
                return ResourceManager.GetString("Language_Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Language_Czech {
            get {
                return ResourceManager.GetString("Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Language_Danish {
            get {
                return ResourceManager.GetString("Language_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Language_Dutch {
            get {
                return ResourceManager.GetString("Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string Language_Estonian {
            get {
                return ResourceManager.GetString("Language_Estonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Language_Finnish {
            get {
                return ResourceManager.GetString("Language_Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (formal).
        /// </summary>
        public static string Language_GermanFormal {
            get {
                return ResourceManager.GetString("Language_GermanFormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (informal).
        /// </summary>
        public static string Language_GermanInformal {
            get {
                return ResourceManager.GetString("Language_GermanInformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string Language_Greek {
            get {
                return ResourceManager.GetString("Language_Greek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string Language_Hungarian {
            get {
                return ResourceManager.GetString("Language_Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Language_Italian {
            get {
                return ResourceManager.GetString("Language_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string Language_Norwegian {
            get {
                return ResourceManager.GetString("Language_Norwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Language_Polish {
            get {
                return ResourceManager.GetString("Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Language_Portuguese {
            get {
                return ResourceManager.GetString("Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string Language_Swedish {
            get {
                return ResourceManager.GetString("Language_Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Language_Turkish {
            get {
                return ResourceManager.GetString("Language_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Language_Ukrainian {
            get {
                return ResourceManager.GetString("Language_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string LogicAction_Field {
            get {
                return ResourceManager.GetString("LogicAction_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string LogicAction_Hidden {
            get {
                return ResourceManager.GetString("LogicAction_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string ProgressBar_Percentage {
            get {
                return ResourceManager.GetString("ProgressBar_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportion.
        /// </summary>
        public static string ProgressBar_Proportion {
            get {
                return ResourceManager.GetString("ProgressBar_Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string Shape_Cat {
            get {
                return ResourceManager.GetString("Shape_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Shape_Circle {
            get {
                return ResourceManager.GetString("Shape_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Shape_Cloud {
            get {
                return ResourceManager.GetString("Shape_Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown.
        /// </summary>
        public static string Shape_Crown {
            get {
                return ResourceManager.GetString("Shape_Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Shape_Dog {
            get {
                return ResourceManager.GetString("Shape_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droplet.
        /// </summary>
        public static string Shape_Droplet {
            get {
                return ResourceManager.GetString("Shape_Droplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string Shape_Flag {
            get {
                return ResourceManager.GetString("Shape_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart.
        /// </summary>
        public static string Shape_Heart {
            get {
                return ResourceManager.GetString("Shape_Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightbulb.
        /// </summary>
        public static string Shape_Lightbulb {
            get {
                return ResourceManager.GetString("Shape_Lightbulb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencil.
        /// </summary>
        public static string Shape_Pencil {
            get {
                return ResourceManager.GetString("Shape_Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skull.
        /// </summary>
        public static string Shape_Skull {
            get {
                return ResourceManager.GetString("Shape_Skull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Shape_Star {
            get {
                return ResourceManager.GetString("Shape_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderbult.
        /// </summary>
        public static string Shape_Thunderbult {
            get {
                return ResourceManager.GetString("Shape_Thunderbult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick.
        /// </summary>
        public static string Shape_Tick {
            get {
                return ResourceManager.GetString("Shape_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophy.
        /// </summary>
        public static string Shape_Trophy {
            get {
                return ResourceManager.GetString("Shape_Trophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Shape_Up {
            get {
                return ResourceManager.GetString("Shape_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Shape_User {
            get {
                return ResourceManager.GetString("Shape_User", resourceCulture);
            }
        }
    }
}
