//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typeform.Sdk.CSharp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Typeform.Sdk.CSharp.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List {2} already contains the value &apos;{1}&apos; provided in {0}..
        /// </summary>
        public static string Guard_ForDuplicateItemsInList {
            get {
                return ResourceManager.GetString("Guard_ForDuplicateItemsInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided ({1}) for &apos;{0}&apos; is above the maximum value of {2}..
        /// </summary>
        public static string Guard_ForMaxValue {
            get {
                return ResourceManager.GetString("Guard_ForMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided ({1}) for &apos;{0}&apos; is below the minimum value of {2}..
        /// </summary>
        public static string Guard_ForMinValue {
            get {
                return ResourceManager.GetString("Guard_ForMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null, empty, or whitespace..
        /// </summary>
        public static string Guard_ForNullOrEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Guard_ForNullOrEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        public static string Guard_ForNullValue {
            get {
                return ResourceManager.GetString("Guard_ForNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Failed while building the form..
        /// </summary>
        public static string Validation_FormCreationException {
            get {
                return ResourceManager.GetString("Validation_FormCreationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is required..
        /// </summary>
        public static string Validation_RequiredProperty {
            get {
                return ResourceManager.GetString("Validation_RequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; requires one..
        /// </summary>
        public static string Validation_RequiresOne {
            get {
                return ResourceManager.GetString("Validation_RequiresOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Workspace Id is required..
        /// </summary>
        public static string Validation_WorkspaceUpdateBuilder_MissingWorkspaceId {
            get {
                return ResourceManager.GetString("Validation_WorkspaceUpdateBuilder_MissingWorkspaceId", resourceCulture);
            }
        }
    }
}
